apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: fraud-detector
  namespace: fraud-detection
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: "rhaiis-sklearn"
      storage:
        path: fraud-detector-openshift/models
        pathPrefix: https://github.com/miqbal-rh/fraud-detection-deployments.git#refs/heads/main
        storageSource: Git
